"""
Action-Plan Agent — turns a TaxBreakdown into concrete next steps + a report.

Receives a TaxBreakdown message, returns an ActionPlan message (which
includes a report_download_url pointing at a PDF generated by this agent).

Owner: Member 4 (also owns the PDF template).
"""

from uagents import Agent, Context

from agents.common.models import TaxBreakdown, ActionPlan
from agents.common import tax_rules

actionplan_agent = Agent(
    name="tax_actionplan_agent",
    seed="ACTIONPLAN_AGENT_SEED",  # TODO: load from .env, must be unique & secret
    port=8003,
    endpoint=["http://127.0.0.1:8003/submit"],
)


@actionplan_agent.on_message(model=TaxBreakdown, replies=ActionPlan)
async def handle_tax_breakdown(ctx: Context, sender: str, msg: TaxBreakdown):
    ctx.logger.info(f"Received TaxBreakdown from {sender}: {msg}")

    # TODO:
    #   1. schedule = tax_rules.build_advance_tax_schedule(msg.net_tax_payable, ...)
    #   2. note = tax_rules.build_optimization_note(msg.taxable_income, msg.net_tax_payable)
    #   3. generate a PDF from `msg` + schedule + note, save to /reports/<id>.pdf
    #   4. reply with an ActionPlan(...) including report_download_url

    raise NotImplementedError("TODO: build action plan + PDF and reply")


if __name__ == "__main__":
    actionplan_agent.run()
