"""
Action-Plan Agent — turns a TaxBreakdown into concrete next steps + a report.

Receives a TaxBreakdown message, returns an ActionPlan message (which
includes a report_download_url pointing at a PDF generated by this agent).

Owner: Member 4 (also owns the PDF template).

STATUS: JSON action-plan logic is wired and working (schedule + optimization
note, using the same tax_rules functions as the FastAPI backend). PDF
generation is still a TODO for Member 4 — report_download_url is a
placeholder path until that's added; it doesn't point at a real file yet.
"""

import os
import uuid
from datetime import datetime

from uagents import Agent, Context

from agents.common.models import TaxBreakdown, ActionPlan
from agents.common import tax_rules

actionplan_agent = Agent(
    name="tax_actionplan_agent",
    seed=os.getenv("ACTIONPLAN_AGENT_SEED", "change-me-to-a-random-string"),
    port=8003,
    endpoint=["http://127.0.0.1:8003/submit"],
)

# NOTE: hardcoded to 2026 for the demo (FY2026-27 advance-tax cycle) —
# same assumption used in backend/routers/tax.py. Swap for a real
# "current FY" calc if there's time before the deadline.
FINANCIAL_YEAR_START = 2026


@actionplan_agent.on_message(model=TaxBreakdown, replies=ActionPlan)
async def handle_tax_breakdown(ctx: Context, sender: str, msg: TaxBreakdown):
    ctx.logger.info(f"Received TaxBreakdown from {sender}: {msg}")

    schedule = tax_rules.build_advance_tax_schedule(msg.net_tax_payable, FINANCIAL_YEAR_START)
    note = tax_rules.build_optimization_note(msg.taxable_income, msg.net_tax_payable)

    report_id = str(uuid.uuid4())

    # TODO(Member 4): generate a real PDF from msg + schedule + note, save to
    # /reports/<report_id>.pdf, and serve it from backend/routers/tax.py's
    # GET /report/{id}/download. Until then this is a placeholder path —
    # the JSON action plan itself is fully correct and testable right now.
    report_download_url = f"/api/tax/report/{report_id}/download"

    action_plan = ActionPlan(
        filing_deadline=f"{FINANCIAL_YEAR_START + 1}-{tax_rules.ITR_FILING_DEADLINE_MONTH_DAY}",
        advance_tax_required=len(schedule) > 0,
        advance_tax_schedule=schedule,
        optimization_note=note,
        report_download_url=report_download_url,
    )

    await ctx.send(sender, action_plan)


if __name__ == "__main__":
    actionplan_agent.run()